name: CI - Kafka Accelerator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Git Checkout 
      run: echo Git Checkout Successfully !!
    
    - name: Maven Build 
      run: echo Maven Build Completed Successfully !!